// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Remote.Func
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RemoteFunctionInterfaceMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RemoteFunctionInterfaceMessage GetRootAsRemoteFunctionInterfaceMessage(ByteBuffer _bb) { return GetRootAsRemoteFunctionInterfaceMessage(_bb, new RemoteFunctionInterfaceMessage()); }
  public static RemoteFunctionInterfaceMessage GetRootAsRemoteFunctionInterfaceMessage(ByteBuffer _bb, RemoteFunctionInterfaceMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRemoteFunctionInterfaceMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RemoteFunctionInterfaceMessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RemoteFunctionInterfaceMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FromLogicBlockId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFromLogicBlockIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFromLogicBlockIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFromLogicBlockIdArray() { return __p.__vector_as_array<byte>(4); }
  public string FromInterfaceIdentifier { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFromInterfaceIdentifierBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFromInterfaceIdentifierBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFromInterfaceIdentifierArray() { return __p.__vector_as_array<byte>(6); }
  public string ToLogicBlockId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetToLogicBlockIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetToLogicBlockIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetToLogicBlockIdArray() { return __p.__vector_as_array<byte>(8); }
  public string ToInterfaceIdentifier { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetToInterfaceIdentifierBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetToInterfaceIdentifierBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetToInterfaceIdentifierArray() { return __p.__vector_as_array<byte>(10); }
  public string PayloadTypeFullName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPayloadTypeFullNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetPayloadTypeFullNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetPayloadTypeFullNameArray() { return __p.__vector_as_array<byte>(12); }
  public byte PayloadData(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int PayloadDataLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPayloadDataBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetPayloadDataBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetPayloadDataArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<Vion.Contracts.FlatBuffers.Remote.Func.RemoteFunctionInterfaceMessage> CreateRemoteFunctionInterfaceMessage(FlatBufferBuilder builder,
      StringOffset from_logic_block_idOffset = default(StringOffset),
      StringOffset from_interface_identifierOffset = default(StringOffset),
      StringOffset to_logic_block_idOffset = default(StringOffset),
      StringOffset to_interface_identifierOffset = default(StringOffset),
      StringOffset payload_type_full_nameOffset = default(StringOffset),
      VectorOffset payload_dataOffset = default(VectorOffset)) {
    builder.StartTable(6);
    RemoteFunctionInterfaceMessage.AddPayloadData(builder, payload_dataOffset);
    RemoteFunctionInterfaceMessage.AddPayloadTypeFullName(builder, payload_type_full_nameOffset);
    RemoteFunctionInterfaceMessage.AddToInterfaceIdentifier(builder, to_interface_identifierOffset);
    RemoteFunctionInterfaceMessage.AddToLogicBlockId(builder, to_logic_block_idOffset);
    RemoteFunctionInterfaceMessage.AddFromInterfaceIdentifier(builder, from_interface_identifierOffset);
    RemoteFunctionInterfaceMessage.AddFromLogicBlockId(builder, from_logic_block_idOffset);
    return RemoteFunctionInterfaceMessage.EndRemoteFunctionInterfaceMessage(builder);
  }

  public static void StartRemoteFunctionInterfaceMessage(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddFromLogicBlockId(FlatBufferBuilder builder, StringOffset fromLogicBlockIdOffset) { builder.AddOffset(0, fromLogicBlockIdOffset.Value, 0); }
  public static void AddFromInterfaceIdentifier(FlatBufferBuilder builder, StringOffset fromInterfaceIdentifierOffset) { builder.AddOffset(1, fromInterfaceIdentifierOffset.Value, 0); }
  public static void AddToLogicBlockId(FlatBufferBuilder builder, StringOffset toLogicBlockIdOffset) { builder.AddOffset(2, toLogicBlockIdOffset.Value, 0); }
  public static void AddToInterfaceIdentifier(FlatBufferBuilder builder, StringOffset toInterfaceIdentifierOffset) { builder.AddOffset(3, toInterfaceIdentifierOffset.Value, 0); }
  public static void AddPayloadTypeFullName(FlatBufferBuilder builder, StringOffset payloadTypeFullNameOffset) { builder.AddOffset(4, payloadTypeFullNameOffset.Value, 0); }
  public static void AddPayloadData(FlatBufferBuilder builder, VectorOffset payloadDataOffset) { builder.AddOffset(5, payloadDataOffset.Value, 0); }
  public static VectorOffset CreatePayloadDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePayloadDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePayloadDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePayloadDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPayloadDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Vion.Contracts.FlatBuffers.Remote.Func.RemoteFunctionInterfaceMessage> EndRemoteFunctionInterfaceMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Remote.Func.RemoteFunctionInterfaceMessage>(o);
  }
  public static void FinishRemoteFunctionInterfaceMessageBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Remote.Func.RemoteFunctionInterfaceMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRemoteFunctionInterfaceMessageBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Remote.Func.RemoteFunctionInterfaceMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RemoteFunctionInterfaceMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*FromLogicBlockId*/, false)
      && verifier.VerifyString(tablePos, 6 /*FromInterfaceIdentifier*/, false)
      && verifier.VerifyString(tablePos, 8 /*ToLogicBlockId*/, false)
      && verifier.VerifyString(tablePos, 10 /*ToInterfaceIdentifier*/, false)
      && verifier.VerifyString(tablePos, 12 /*PayloadTypeFullName*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*PayloadData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
