// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Sw.MeasuringPoint
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetMeasuringPointPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetMeasuringPointPayload GetRootAsGetMeasuringPointPayload(ByteBuffer _bb) { return GetRootAsGetMeasuringPointPayload(_bb, new GetMeasuringPointPayload()); }
  public static GetMeasuringPointPayload GetRootAsGetMeasuringPointPayload(ByteBuffer _bb, GetMeasuringPointPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetMeasuringPointPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetMeasuringPointPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetMeasuringPointPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetMeasuringPointPayload(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.GetMeasuringPointPayload> EndGetMeasuringPointPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.GetMeasuringPointPayload>(o);
  }
  public static void FinishGetMeasuringPointPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.GetMeasuringPointPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetMeasuringPointPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.GetMeasuringPointPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetMeasuringPointPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
