// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Sw.MeasuringPoint
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MeasuringPointStatePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MeasuringPointStatePayload GetRootAsMeasuringPointStatePayload(ByteBuffer _bb) { return GetRootAsMeasuringPointStatePayload(_bb, new MeasuringPointStatePayload()); }
  public static MeasuringPointStatePayload GetRootAsMeasuringPointStatePayload(ByteBuffer _bb, MeasuringPointStatePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMeasuringPointStatePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MeasuringPointStatePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MeasuringPointStatePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.PropertyValue? Value { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.PropertyValue?)(new Vion.Contracts.FlatBuffers.Common.PropertyValue()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.MeasuringPointStatePayload> CreateMeasuringPointStatePayload(FlatBufferBuilder builder,
      Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> valueOffset = default(Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue>)) {
    builder.StartTable(1);
    MeasuringPointStatePayload.AddValue(builder, valueOffset);
    return MeasuringPointStatePayload.EndMeasuringPointStatePayload(builder);
  }

  public static void StartMeasuringPointStatePayload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> valueOffset) { builder.AddOffset(0, valueOffset.Value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.MeasuringPointStatePayload> EndMeasuringPointStatePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.MeasuringPointStatePayload>(o);
  }
  public static void FinishMeasuringPointStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.MeasuringPointStatePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMeasuringPointStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.MeasuringPoint.MeasuringPointStatePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MeasuringPointStatePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Value*/, Vion.Contracts.FlatBuffers.Common.PropertyValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
