// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Di
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DiStatePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DiStatePayload GetRootAsDiStatePayload(ByteBuffer _bb) { return GetRootAsDiStatePayload(_bb, new DiStatePayload()); }
  public static DiStatePayload GetRootAsDiStatePayload(ByteBuffer _bb, DiStatePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyDiStatePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, DiStatePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DiStatePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string HardwareBlockInstanceId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHardwareBlockInstanceIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetHardwareBlockInstanceIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetHardwareBlockInstanceIdArray() { return __p.__vector_as_array<byte>(4); }
  public string EndpointIdentifier { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEndpointIdentifierBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEndpointIdentifierBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEndpointIdentifierArray() { return __p.__vector_as_array<byte>(6); }
  public bool Value { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Di.DiStatePayload> CreateDiStatePayload(FlatBufferBuilder builder,
      StringOffset hardware_block_instance_idOffset = default(StringOffset),
      StringOffset endpoint_identifierOffset = default(StringOffset),
      bool value = false) {
    builder.StartTable(3);
    DiStatePayload.AddEndpointIdentifier(builder, endpoint_identifierOffset);
    DiStatePayload.AddHardwareBlockInstanceId(builder, hardware_block_instance_idOffset);
    DiStatePayload.AddValue(builder, value);
    return DiStatePayload.EndDiStatePayload(builder);
  }

  public static void StartDiStatePayload(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHardwareBlockInstanceId(FlatBufferBuilder builder, StringOffset hardwareBlockInstanceIdOffset) { builder.AddOffset(0, hardwareBlockInstanceIdOffset.Value, 0); }
  public static void AddEndpointIdentifier(FlatBufferBuilder builder, StringOffset endpointIdentifierOffset) { builder.AddOffset(1, endpointIdentifierOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(2, value, false); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Di.DiStatePayload> EndDiStatePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Di.DiStatePayload>(o);
  }
  public static void FinishDiStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Di.DiStatePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDiStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Di.DiStatePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class DiStatePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*HardwareBlockInstanceId*/, false)
      && verifier.VerifyString(tablePos, 6 /*EndpointIdentifier*/, false)
      && verifier.VerifyField(tablePos, 8 /*Value*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
