namespace Vion.Contracts.FlatBuffers.System.Health;

enum ConnectionStatus : byte {
  Unknown = 0,
  Offline = 1,
  Online = 2
}

enum HealthStatus : byte {
  Unknown = 0,
  Unhealthy = 1,
  Healthy = 2
}

table Component {
  name:string (required);
  connection_status:ConnectionStatus;
  health_status:HealthStatus;
  since_unix_ms:long; // 0 means unknown (e.g., from last will message) or not applicable
  reason:string; // Nullable - reason for current health state
  sub_components:[Component]; // Nullable - list of subcomponents/internal services
}

table ComponentHealthStatusPayload {
  component:Component (required);
}

root_type ComponentHealthStatusPayload;
