// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Sw.Property
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetPropertyPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetPropertyPayload GetRootAsGetPropertyPayload(ByteBuffer _bb) { return GetRootAsGetPropertyPayload(_bb, new GetPropertyPayload()); }
  public static GetPropertyPayload GetRootAsGetPropertyPayload(ByteBuffer _bb, GetPropertyPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetPropertyPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetPropertyPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetPropertyPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetPropertyPayload(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Vion.Contracts.FlatBuffers.Sw.Property.GetPropertyPayload> EndGetPropertyPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Sw.Property.GetPropertyPayload>(o);
  }
  public static void FinishGetPropertyPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.Property.GetPropertyPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetPropertyPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.Property.GetPropertyPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetPropertyPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
