// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Sw.Property
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetPropertyResponsePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetPropertyResponsePayload GetRootAsSetPropertyResponsePayload(ByteBuffer _bb) { return GetRootAsSetPropertyResponsePayload(_bb, new SetPropertyResponsePayload()); }
  public static SetPropertyResponsePayload GetRootAsSetPropertyResponsePayload(ByteBuffer _bb, SetPropertyResponsePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetPropertyResponsePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetPropertyResponsePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetPropertyResponsePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.CommonValue? Value { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.CommonValue?)(new Vion.Contracts.FlatBuffers.Common.CommonValue()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Vion.Contracts.FlatBuffers.Sw.Property.SetPropertyResponsePayload> CreateSetPropertyResponsePayload(FlatBufferBuilder builder,
      Offset<Vion.Contracts.FlatBuffers.Common.CommonValue> valueOffset = default(Offset<Vion.Contracts.FlatBuffers.Common.CommonValue>)) {
    builder.StartTable(1);
    SetPropertyResponsePayload.AddValue(builder, valueOffset);
    return SetPropertyResponsePayload.EndSetPropertyResponsePayload(builder);
  }

  public static void StartSetPropertyResponsePayload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.CommonValue> valueOffset) { builder.AddOffset(0, valueOffset.Value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Sw.Property.SetPropertyResponsePayload> EndSetPropertyResponsePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Sw.Property.SetPropertyResponsePayload>(o);
  }
  public static void FinishSetPropertyResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.Property.SetPropertyResponsePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetPropertyResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Sw.Property.SetPropertyResponsePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetPropertyResponsePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Value*/, Vion.Contracts.FlatBuffers.Common.CommonValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
