// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.System.Health
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ComponentHealthStatusPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ComponentHealthStatusPayload GetRootAsComponentHealthStatusPayload(ByteBuffer _bb) { return GetRootAsComponentHealthStatusPayload(_bb, new ComponentHealthStatusPayload()); }
  public static ComponentHealthStatusPayload GetRootAsComponentHealthStatusPayload(ByteBuffer _bb, ComponentHealthStatusPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyComponentHealthStatusPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ComponentHealthStatusPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ComponentHealthStatusPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.System.Health.Component? Component { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.System.Health.Component?)(new Vion.Contracts.FlatBuffers.System.Health.Component()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Vion.Contracts.FlatBuffers.System.Health.ComponentHealthStatusPayload> CreateComponentHealthStatusPayload(FlatBufferBuilder builder,
      Offset<Vion.Contracts.FlatBuffers.System.Health.Component> componentOffset = default(Offset<Vion.Contracts.FlatBuffers.System.Health.Component>)) {
    builder.StartTable(1);
    ComponentHealthStatusPayload.AddComponent(builder, componentOffset);
    return ComponentHealthStatusPayload.EndComponentHealthStatusPayload(builder);
  }

  public static void StartComponentHealthStatusPayload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddComponent(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.System.Health.Component> componentOffset) { builder.AddOffset(0, componentOffset.Value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.System.Health.ComponentHealthStatusPayload> EndComponentHealthStatusPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // component
    return new Offset<Vion.Contracts.FlatBuffers.System.Health.ComponentHealthStatusPayload>(o);
  }
  public static void FinishComponentHealthStatusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.System.Health.ComponentHealthStatusPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedComponentHealthStatusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.System.Health.ComponentHealthStatusPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ComponentHealthStatusPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Component*/, Vion.Contracts.FlatBuffers.System.Health.ComponentVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
