// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.System.Health
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Component : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Component GetRootAsComponent(ByteBuffer _bb) { return GetRootAsComponent(_bb, new Component()); }
  public static Component GetRootAsComponent(ByteBuffer _bb, Component obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Component __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus ConnectionStatus { get { int o = __p.__offset(6); return o != 0 ? (Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus)__p.bb.GetSbyte(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus.Unknown; } }
  public Vion.Contracts.FlatBuffers.System.Health.HealthStatus HealthStatus { get { int o = __p.__offset(8); return o != 0 ? (Vion.Contracts.FlatBuffers.System.Health.HealthStatus)__p.bb.GetSbyte(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.System.Health.HealthStatus.Unknown; } }
  public long SinceUnixMs { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string Reason { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(12); }
  public Vion.Contracts.FlatBuffers.System.Health.Component? SubComponents(int j) { int o = __p.__offset(14); return o != 0 ? (Vion.Contracts.FlatBuffers.System.Health.Component?)(new Vion.Contracts.FlatBuffers.System.Health.Component()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SubComponentsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Vion.Contracts.FlatBuffers.System.Health.Component> CreateComponent(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus connection_status = Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus.Unknown,
      Vion.Contracts.FlatBuffers.System.Health.HealthStatus health_status = Vion.Contracts.FlatBuffers.System.Health.HealthStatus.Unknown,
      long since_unix_ms = 0,
      StringOffset reasonOffset = default(StringOffset),
      VectorOffset sub_componentsOffset = default(VectorOffset)) {
    builder.StartTable(6);
    Component.AddSinceUnixMs(builder, since_unix_ms);
    Component.AddSubComponents(builder, sub_componentsOffset);
    Component.AddReason(builder, reasonOffset);
    Component.AddName(builder, nameOffset);
    Component.AddHealthStatus(builder, health_status);
    Component.AddConnectionStatus(builder, connection_status);
    return Component.EndComponent(builder);
  }

  public static void StartComponent(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddConnectionStatus(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus connectionStatus) { builder.AddSbyte(1, (sbyte)connectionStatus, 0); }
  public static void AddHealthStatus(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.System.Health.HealthStatus healthStatus) { builder.AddSbyte(2, (sbyte)healthStatus, 0); }
  public static void AddSinceUnixMs(FlatBufferBuilder builder, long sinceUnixMs) { builder.AddLong(3, sinceUnixMs, 0); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(4, reasonOffset.Value, 0); }
  public static void AddSubComponents(FlatBufferBuilder builder, VectorOffset subComponentsOffset) { builder.AddOffset(5, subComponentsOffset.Value, 0); }
  public static VectorOffset CreateSubComponentsVector(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.System.Health.Component>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSubComponentsVectorBlock(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.System.Health.Component>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubComponentsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Vion.Contracts.FlatBuffers.System.Health.Component>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubComponentsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Vion.Contracts.FlatBuffers.System.Health.Component>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSubComponentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Vion.Contracts.FlatBuffers.System.Health.Component> EndComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    return new Offset<Vion.Contracts.FlatBuffers.System.Health.Component>(o);
  }
}


static public class ComponentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, true)
      && verifier.VerifyField(tablePos, 6 /*ConnectionStatus*/, 1 /*Vion.Contracts.FlatBuffers.System.Health.ConnectionStatus*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*HealthStatus*/, 1 /*Vion.Contracts.FlatBuffers.System.Health.HealthStatus*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*SinceUnixMs*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 12 /*Reason*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*SubComponents*/, Vion.Contracts.FlatBuffers.System.Health.ComponentVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
