// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.System.Health
{

public enum ConnectionStatus : sbyte
{
  Unknown = 0,
  Offline = 1,
  Online = 2,
};


}
