// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.System.Health
{

public enum HealthStatus : sbyte
{
  Unknown = 0,
  Unhealthy = 1,
  Healthy = 2,
};


}
