namespace Vion.Contracts.FlatBuffers.Hw.Modbus;

enum ModbusFunctionCode : ubyte {
    None = 0x00,                      // FlatBuffers requires a 0 value for enum defaults
    ReadCoils = 0x01,                 // FC01
    ReadDiscreteInputs = 0x02,        // FC02
    ReadHoldingRegisters = 0x03,      // FC03
    ReadInputRegisters = 0x04,        // FC04
    WriteSingleCoil = 0x05,           // FC05
    WriteSingleRegister = 0x06,       // FC06
    WriteMultipleCoils = 0x0F,        // FC15
    WriteMultipleRegisters = 0x10,    // FC16
}