namespace Vion.Contracts.FlatBuffers.Hw.Modbus;

enum ModbusResponseCode : ubyte {
    Ok = 0x00, // The request was successful.
    IllegalFunction = 0x01, // The function code received in the query is not an allowable action for the server.
    IllegalDataAddress = 0x02, // The data address received in the query is not an allowable address for the server.
    IllegalDataValue = 0x03, // A value contained in the query data field is not an allowable value for server.
    ServerDeviceFailure = 0x04, // An unrecoverable error occurred while the server was attempting to perform the requested action.
    Acknowledge = 0x05, //Specialized use in conjunction with programming commands. The server has accepted the request and is processing it, but a long duration of time will be required to do so.
    ServerDeviceBusy = 0x06, // Specialized use in conjunction with programming commands. The engaged in processing a long–duration program command.
    MemoryParityError = 0x8, // Specialized use in conjunction with function codes 20 and 21 and reference type 6, to indicate that the extended file area failed to pass a consistency check.
    GatewayPathUnavailable = 0x0A, // Specialized use in conjunction with gateways, indicates that the gateway was unable to allocate an internal communication path from the input port to the output port for processing the request.
    GatewayTargetDeviceFailedToRespond = 0x0B, // Specialized use in conjunction with gateways, indicates that no response was obtained from the target device.
    NonProtocolError = 0xFF, // An error unrelated to the Modbus protocol, e.g., transport or infrastructure failures.
}