// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Ai
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AiStatePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AiStatePayload GetRootAsAiStatePayload(ByteBuffer _bb) { return GetRootAsAiStatePayload(_bb, new AiStatePayload()); }
  public static AiStatePayload GetRootAsAiStatePayload(ByteBuffer _bb, AiStatePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAiStatePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AiStatePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AiStatePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string HardwareBlockInstanceId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHardwareBlockInstanceIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetHardwareBlockInstanceIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetHardwareBlockInstanceIdArray() { return __p.__vector_as_array<byte>(4); }
  public string EndpointIdentifier { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEndpointIdentifierBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEndpointIdentifierBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEndpointIdentifierArray() { return __p.__vector_as_array<byte>(6); }
  public double Value { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Ai.AiStatePayload> CreateAiStatePayload(FlatBufferBuilder builder,
      StringOffset hardware_block_instance_idOffset = default(StringOffset),
      StringOffset endpoint_identifierOffset = default(StringOffset),
      double value = 0.0) {
    builder.StartTable(3);
    AiStatePayload.AddValue(builder, value);
    AiStatePayload.AddEndpointIdentifier(builder, endpoint_identifierOffset);
    AiStatePayload.AddHardwareBlockInstanceId(builder, hardware_block_instance_idOffset);
    return AiStatePayload.EndAiStatePayload(builder);
  }

  public static void StartAiStatePayload(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHardwareBlockInstanceId(FlatBufferBuilder builder, StringOffset hardwareBlockInstanceIdOffset) { builder.AddOffset(0, hardwareBlockInstanceIdOffset.Value, 0); }
  public static void AddEndpointIdentifier(FlatBufferBuilder builder, StringOffset endpointIdentifierOffset) { builder.AddOffset(1, endpointIdentifierOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(2, value, 0.0); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Ai.AiStatePayload> EndAiStatePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Ai.AiStatePayload>(o);
  }
  public static void FinishAiStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Ai.AiStatePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAiStatePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Ai.AiStatePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AiStatePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*HardwareBlockInstanceId*/, false)
      && verifier.VerifyString(tablePos, 6 /*EndpointIdentifier*/, false)
      && verifier.VerifyField(tablePos, 8 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
