// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CommonValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CommonValue GetRootAsCommonValue(ByteBuffer _bb) { return GetRootAsCommonValue(_bb, new CommonValue()); }
  public static CommonValue GetRootAsCommonValue(ByteBuffer _bb, CommonValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CommonValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.CommonValueKind Kind { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.CommonValueKind)__p.bb.GetSbyte(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Common.CommonValueKind.None; } }
  public int IntValue { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public double DoubleValue { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public bool BoolValue { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string StringValue { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStringValueBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetStringValueBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetStringValueArray() { return __p.__vector_as_array<byte>(12); }
  public long DatetimeUnixMs { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long TimespanTicks { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.CommonValue> CreateCommonValue(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Common.CommonValueKind kind = Vion.Contracts.FlatBuffers.Common.CommonValueKind.None,
      int int_value = 0,
      double double_value = 0.0,
      bool bool_value = false,
      StringOffset string_valueOffset = default(StringOffset),
      long datetime_unix_ms = 0,
      long timespan_ticks = 0) {
    builder.StartTable(7);
    CommonValue.AddTimespanTicks(builder, timespan_ticks);
    CommonValue.AddDatetimeUnixMs(builder, datetime_unix_ms);
    CommonValue.AddDoubleValue(builder, double_value);
    CommonValue.AddStringValue(builder, string_valueOffset);
    CommonValue.AddIntValue(builder, int_value);
    CommonValue.AddBoolValue(builder, bool_value);
    CommonValue.AddKind(builder, kind);
    return CommonValue.EndCommonValue(builder);
  }

  public static void StartCommonValue(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddKind(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Common.CommonValueKind kind) { builder.AddSbyte(0, (sbyte)kind, 0); }
  public static void AddIntValue(FlatBufferBuilder builder, int intValue) { builder.AddInt(1, intValue, 0); }
  public static void AddDoubleValue(FlatBufferBuilder builder, double doubleValue) { builder.AddDouble(2, doubleValue, 0.0); }
  public static void AddBoolValue(FlatBufferBuilder builder, bool boolValue) { builder.AddBool(3, boolValue, false); }
  public static void AddStringValue(FlatBufferBuilder builder, StringOffset stringValueOffset) { builder.AddOffset(4, stringValueOffset.Value, 0); }
  public static void AddDatetimeUnixMs(FlatBufferBuilder builder, long datetimeUnixMs) { builder.AddLong(5, datetimeUnixMs, 0); }
  public static void AddTimespanTicks(FlatBufferBuilder builder, long timespanTicks) { builder.AddLong(6, timespanTicks, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.CommonValue> EndCommonValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.CommonValue>(o);
  }
}


static public class CommonValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Kind*/, 1 /*Vion.Contracts.FlatBuffers.Common.CommonValueKind*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*IntValue*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*DoubleValue*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*BoolValue*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 12 /*StringValue*/, false)
      && verifier.VerifyField(tablePos, 14 /*DatetimeUnixMs*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 16 /*TimespanTicks*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
