// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

public enum CommonValueKind : sbyte
{
  None = 0,
  Int = 1,
  Double = 2,
  Bool = 3,
  String = 4,
  DateTime = 5,
  TimeSpan = 6,
};


}
