// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DateTimeVal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DateTimeVal GetRootAsDateTimeVal(ByteBuffer _bb) { return GetRootAsDateTimeVal(_bb, new DateTimeVal()); }
  public static DateTimeVal GetRootAsDateTimeVal(ByteBuffer _bb, DateTimeVal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DateTimeVal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UnixMs { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.DateTimeVal> CreateDateTimeVal(FlatBufferBuilder builder,
      long unix_ms = 0) {
    builder.StartTable(1);
    DateTimeVal.AddUnixMs(builder, unix_ms);
    return DateTimeVal.EndDateTimeVal(builder);
  }

  public static void StartDateTimeVal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUnixMs(FlatBufferBuilder builder, long unixMs) { builder.AddLong(0, unixMs, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.DateTimeVal> EndDateTimeVal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.DateTimeVal>(o);
  }
}


static public class DateTimeValVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UnixMs*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
