// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DurationArray : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DurationArray GetRootAsDurationArray(ByteBuffer _bb) { return GetRootAsDurationArray(_bb, new DurationArray()); }
  public static DurationArray GetRootAsDurationArray(ByteBuffer _bb, DurationArray obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DurationArray __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Ticks(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int TicksLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetTicksBytes() { return __p.__vector_as_span<long>(4, 8); }
#else
  public ArraySegment<byte>? GetTicksBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public long[] GetTicksArray() { return __p.__vector_as_array<long>(4); }
  public bool Present(int j) { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(__p.__vector(o) + j * 1) : false; }
  public int PresentLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<bool> GetPresentBytes() { return __p.__vector_as_span<bool>(6, 1); }
#else
  public ArraySegment<byte>? GetPresentBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public bool[] GetPresentArray() { return __p.__vector_as_array<bool>(6); }

  public static Offset<Vion.Contracts.FlatBuffers.Common.DurationArray> CreateDurationArray(FlatBufferBuilder builder,
      VectorOffset ticksOffset = default(VectorOffset),
      VectorOffset presentOffset = default(VectorOffset)) {
    builder.StartTable(2);
    DurationArray.AddPresent(builder, presentOffset);
    DurationArray.AddTicks(builder, ticksOffset);
    return DurationArray.EndDurationArray(builder);
  }

  public static void StartDurationArray(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTicks(FlatBufferBuilder builder, VectorOffset ticksOffset) { builder.AddOffset(0, ticksOffset.Value, 0); }
  public static VectorOffset CreateTicksVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTicksVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTicksVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTicksVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTicksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddPresent(FlatBufferBuilder builder, VectorOffset presentOffset) { builder.AddOffset(1, presentOffset.Value, 0); }
  public static VectorOffset CreatePresentVector(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddBool(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, ArraySegment<bool> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<bool>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPresentVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.DurationArray> EndDurationArray(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.DurationArray>(o);
  }
}


static public class DurationArrayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Ticks*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Present*/, 1 /*bool*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
