// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DurationVal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DurationVal GetRootAsDurationVal(ByteBuffer _bb) { return GetRootAsDurationVal(_bb, new DurationVal()); }
  public static DurationVal GetRootAsDurationVal(ByteBuffer _bb, DurationVal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DurationVal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Ticks { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.DurationVal> CreateDurationVal(FlatBufferBuilder builder,
      long ticks = 0) {
    builder.StartTable(1);
    DurationVal.AddTicks(builder, ticks);
    return DurationVal.EndDurationVal(builder);
  }

  public static void StartDurationVal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTicks(FlatBufferBuilder builder, long ticks) { builder.AddLong(0, ticks, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.DurationVal> EndDurationVal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.DurationVal>(o);
  }
}


static public class DurationValVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ticks*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
