// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LongVal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LongVal GetRootAsLongVal(ByteBuffer _bb) { return GetRootAsLongVal(_bb, new LongVal()); }
  public static LongVal GetRootAsLongVal(ByteBuffer _bb, LongVal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LongVal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.LongVal> CreateLongVal(FlatBufferBuilder builder,
      long value = 0) {
    builder.StartTable(1);
    LongVal.AddValue(builder, value);
    return LongVal.EndLongVal(builder);
  }

  public static void StartLongVal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, long value) { builder.AddLong(0, value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.LongVal> EndLongVal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.LongVal>(o);
  }
}


static public class LongValVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
