// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct NamedValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static NamedValue GetRootAsNamedValue(ByteBuffer _bb) { return GetRootAsNamedValue(_bb, new NamedValue()); }
  public static NamedValue GetRootAsNamedValue(ByteBuffer _bb, NamedValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NamedValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Vion.Contracts.FlatBuffers.Common.PropertyValue? Value { get { int o = __p.__offset(6); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.PropertyValue?)(new Vion.Contracts.FlatBuffers.Common.PropertyValue()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.NamedValue> CreateNamedValue(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> valueOffset = default(Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue>)) {
    builder.StartTable(2);
    NamedValue.AddValue(builder, valueOffset);
    NamedValue.AddName(builder, nameOffset);
    return NamedValue.EndNamedValue(builder);
  }

  public static void StartNamedValue(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.NamedValue> EndNamedValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.NamedValue>(o);
  }
}


static public class NamedValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyTable(tablePos, 6 /*Value*/, Vion.Contracts.FlatBuffers.Common.PropertyValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
