// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PropertyValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static PropertyValue GetRootAsPropertyValue(ByteBuffer _bb) { return GetRootAsPropertyValue(_bb, new PropertyValue()); }
  public static PropertyValue GetRootAsPropertyValue(ByteBuffer _bb, PropertyValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPropertyValue(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PropertyValueVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PropertyValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.ValuePayload PayloadType { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.ValuePayload)__p.bb.Get(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Common.ValuePayload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Vion.Contracts.FlatBuffers.Common.BoolVal PayloadAsBoolVal() { return Payload<Vion.Contracts.FlatBuffers.Common.BoolVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.LongVal PayloadAsLongVal() { return Payload<Vion.Contracts.FlatBuffers.Common.LongVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DoubleVal PayloadAsDoubleVal() { return Payload<Vion.Contracts.FlatBuffers.Common.DoubleVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.StringVal PayloadAsStringVal() { return Payload<Vion.Contracts.FlatBuffers.Common.StringVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DateTimeVal PayloadAsDateTimeVal() { return Payload<Vion.Contracts.FlatBuffers.Common.DateTimeVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DurationVal PayloadAsDurationVal() { return Payload<Vion.Contracts.FlatBuffers.Common.DurationVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.BoolArray PayloadAsBoolArray() { return Payload<Vion.Contracts.FlatBuffers.Common.BoolArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.LongArray PayloadAsLongArray() { return Payload<Vion.Contracts.FlatBuffers.Common.LongArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DoubleArray PayloadAsDoubleArray() { return Payload<Vion.Contracts.FlatBuffers.Common.DoubleArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.StringArray PayloadAsStringArray() { return Payload<Vion.Contracts.FlatBuffers.Common.StringArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DateTimeArray PayloadAsDateTimeArray() { return Payload<Vion.Contracts.FlatBuffers.Common.DateTimeArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.DurationArray PayloadAsDurationArray() { return Payload<Vion.Contracts.FlatBuffers.Common.DurationArray>().Value; }
  public Vion.Contracts.FlatBuffers.Common.StructVal PayloadAsStructVal() { return Payload<Vion.Contracts.FlatBuffers.Common.StructVal>().Value; }
  public Vion.Contracts.FlatBuffers.Common.StructArray PayloadAsStructArray() { return Payload<Vion.Contracts.FlatBuffers.Common.StructArray>().Value; }

  public static Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> CreatePropertyValue(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Common.ValuePayload payload_type = Vion.Contracts.FlatBuffers.Common.ValuePayload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(2);
    PropertyValue.AddPayload(builder, payloadOffset);
    PropertyValue.AddPayloadType(builder, payload_type);
    return PropertyValue.EndPropertyValue(builder);
  }

  public static void StartPropertyValue(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Common.ValuePayload payloadType) { builder.AddByte(0, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(1, payloadOffset, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> EndPropertyValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue>(o);
  }
  public static void FinishPropertyValueBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPropertyValueBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.PropertyValue> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PropertyValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PayloadType*/, 1 /*Vion.Contracts.FlatBuffers.Common.ValuePayload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Payload*/, Vion.Contracts.FlatBuffers.Common.ValuePayloadVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
