// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StructVal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static StructVal GetRootAsStructVal(ByteBuffer _bb) { return GetRootAsStructVal(_bb, new StructVal()); }
  public static StructVal GetRootAsStructVal(ByteBuffer _bb, StructVal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StructVal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.NamedValue? Fields(int j) { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.NamedValue?)(new Vion.Contracts.FlatBuffers.Common.NamedValue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FieldsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Common.StructVal> CreateStructVal(FlatBufferBuilder builder,
      VectorOffset fieldsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    StructVal.AddFields(builder, fieldsOffset);
    return StructVal.EndStructVal(builder);
  }

  public static void StartStructVal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFields(FlatBufferBuilder builder, VectorOffset fieldsOffset) { builder.AddOffset(0, fieldsOffset.Value, 0); }
  public static VectorOffset CreateFieldsVector(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.NamedValue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFieldsVectorBlock(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.NamedValue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFieldsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Vion.Contracts.FlatBuffers.Common.NamedValue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFieldsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Vion.Contracts.FlatBuffers.Common.NamedValue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFieldsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.StructVal> EndStructVal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.StructVal>(o);
  }
}


static public class StructValVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Fields*/, Vion.Contracts.FlatBuffers.Common.NamedValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
