// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StructArray : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static StructArray GetRootAsStructArray(ByteBuffer _bb) { return GetRootAsStructArray(_bb, new StructArray()); }
  public static StructArray GetRootAsStructArray(ByteBuffer _bb, StructArray obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StructArray __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Common.StructVal? Items(int j) { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Common.StructVal?)(new Vion.Contracts.FlatBuffers.Common.StructVal()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public bool Present(int j) { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(__p.__vector(o) + j * 1) : false; }
  public int PresentLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<bool> GetPresentBytes() { return __p.__vector_as_span<bool>(6, 1); }
#else
  public ArraySegment<byte>? GetPresentBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public bool[] GetPresentArray() { return __p.__vector_as_array<bool>(6); }

  public static Offset<Vion.Contracts.FlatBuffers.Common.StructArray> CreateStructArray(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset),
      VectorOffset presentOffset = default(VectorOffset)) {
    builder.StartTable(2);
    StructArray.AddPresent(builder, presentOffset);
    StructArray.AddItems(builder, itemsOffset);
    return StructArray.EndStructArray(builder);
  }

  public static void StartStructArray(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.StructVal>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Common.StructVal>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Vion.Contracts.FlatBuffers.Common.StructVal>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Vion.Contracts.FlatBuffers.Common.StructVal>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPresent(FlatBufferBuilder builder, VectorOffset presentOffset) { builder.AddOffset(1, presentOffset.Value, 0); }
  public static VectorOffset CreatePresentVector(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddBool(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, ArraySegment<bool> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePresentVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<bool>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPresentVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Vion.Contracts.FlatBuffers.Common.StructArray> EndStructArray(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Common.StructArray>(o);
  }
}


static public class StructArrayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Items*/, Vion.Contracts.FlatBuffers.Common.StructValVerify.Verify, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Present*/, 1 /*bool*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
