// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Common
{

public enum ValuePayload : byte
{
  NONE = 0,
  BoolVal = 1,
  LongVal = 2,
  DoubleVal = 3,
  StringVal = 4,
  DateTimeVal = 5,
  DurationVal = 6,
  BoolArray = 7,
  LongArray = 8,
  DoubleArray = 9,
  StringArray = 10,
  DateTimeArray = 11,
  DurationArray = 12,
  StructVal = 13,
  StructArray = 14,
};



static public class ValuePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ValuePayload)typeId)
    {
      case ValuePayload.BoolVal:
        result = Vion.Contracts.FlatBuffers.Common.BoolValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.LongVal:
        result = Vion.Contracts.FlatBuffers.Common.LongValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DoubleVal:
        result = Vion.Contracts.FlatBuffers.Common.DoubleValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.StringVal:
        result = Vion.Contracts.FlatBuffers.Common.StringValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DateTimeVal:
        result = Vion.Contracts.FlatBuffers.Common.DateTimeValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DurationVal:
        result = Vion.Contracts.FlatBuffers.Common.DurationValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.BoolArray:
        result = Vion.Contracts.FlatBuffers.Common.BoolArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.LongArray:
        result = Vion.Contracts.FlatBuffers.Common.LongArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DoubleArray:
        result = Vion.Contracts.FlatBuffers.Common.DoubleArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.StringArray:
        result = Vion.Contracts.FlatBuffers.Common.StringArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DateTimeArray:
        result = Vion.Contracts.FlatBuffers.Common.DateTimeArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.DurationArray:
        result = Vion.Contracts.FlatBuffers.Common.DurationArrayVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.StructVal:
        result = Vion.Contracts.FlatBuffers.Common.StructValVerify.Verify(verifier, tablePos);
        break;
      case ValuePayload.StructArray:
        result = Vion.Contracts.FlatBuffers.Common.StructArrayVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
