// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Do
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetDoPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetDoPayload GetRootAsSetDoPayload(ByteBuffer _bb) { return GetRootAsSetDoPayload(_bb, new SetDoPayload()); }
  public static SetDoPayload GetRootAsSetDoPayload(ByteBuffer _bb, SetDoPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetDoPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetDoPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetDoPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Do.SetDoPayload> CreateSetDoPayload(FlatBufferBuilder builder,
      bool value = false) {
    builder.StartTable(1);
    SetDoPayload.AddValue(builder, value);
    return SetDoPayload.EndSetDoPayload(builder);
  }

  public static void StartSetDoPayload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(0, value, false); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Do.SetDoPayload> EndSetDoPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Do.SetDoPayload>(o);
  }
  public static void FinishSetDoPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Do.SetDoPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetDoPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Do.SetDoPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetDoPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
