// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Modbus
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetModbusResponsePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetModbusResponsePayload GetRootAsGetModbusResponsePayload(ByteBuffer _bb) { return GetRootAsGetModbusResponsePayload(_bb, new GetModbusResponsePayload()); }
  public static GetModbusResponsePayload GetRootAsGetModbusResponsePayload(ByteBuffer _bb, GetModbusResponsePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetModbusResponsePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetModbusResponsePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetModbusResponsePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode ResponseCode { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode)__p.bb.Get(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode.Ok; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }
  public byte Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusResponsePayload> CreateGetModbusResponsePayload(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode response_code = Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode.Ok,
      StringOffset error_messageOffset = default(StringOffset),
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(3);
    GetModbusResponsePayload.AddData(builder, dataOffset);
    GetModbusResponsePayload.AddErrorMessage(builder, error_messageOffset);
    GetModbusResponsePayload.AddResponseCode(builder, response_code);
    return GetModbusResponsePayload.EndGetModbusResponsePayload(builder);
  }

  public static void StartGetModbusResponsePayload(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddResponseCode(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode responseCode) { builder.AddByte(0, (byte)responseCode, 0); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusResponsePayload> EndGetModbusResponsePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusResponsePayload>(o);
  }
  public static void FinishGetModbusResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusResponsePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetModbusResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusResponsePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetModbusResponsePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResponseCode*/, 1 /*Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode*/, 1, false)
      && verifier.VerifyString(tablePos, 6 /*ErrorMessage*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Data*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
