// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Modbus
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetModbusPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetModbusPayload GetRootAsGetModbusPayload(ByteBuffer _bb) { return GetRootAsGetModbusPayload(_bb, new GetModbusPayload()); }
  public static GetModbusPayload GetRootAsGetModbusPayload(ByteBuffer _bb, GetModbusPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetModbusPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetModbusPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetModbusPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode FunctionCode { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode)__p.bb.Get(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode.None; } }
  public byte UnitIdentifier { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort StartingAddress { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort Quantity { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusPayload> CreateGetModbusPayload(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode function_code = Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode.None,
      byte unit_identifier = 0,
      ushort starting_address = 0,
      ushort quantity = 0) {
    builder.StartTable(4);
    GetModbusPayload.AddQuantity(builder, quantity);
    GetModbusPayload.AddStartingAddress(builder, starting_address);
    GetModbusPayload.AddUnitIdentifier(builder, unit_identifier);
    GetModbusPayload.AddFunctionCode(builder, function_code);
    return GetModbusPayload.EndGetModbusPayload(builder);
  }

  public static void StartGetModbusPayload(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddFunctionCode(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode functionCode) { builder.AddByte(0, (byte)functionCode, 0); }
  public static void AddUnitIdentifier(FlatBufferBuilder builder, byte unitIdentifier) { builder.AddByte(1, unitIdentifier, 0); }
  public static void AddStartingAddress(FlatBufferBuilder builder, ushort startingAddress) { builder.AddUshort(2, startingAddress, 0); }
  public static void AddQuantity(FlatBufferBuilder builder, ushort quantity) { builder.AddUshort(3, quantity, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusPayload> EndGetModbusPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusPayload>(o);
  }
  public static void FinishGetModbusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetModbusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.GetModbusPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetModbusPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*FunctionCode*/, 1 /*Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*UnitIdentifier*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*StartingAddress*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Quantity*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
