// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Modbus
{

public enum ModbusResponseCode : byte
{
  Ok = 0,
  IllegalFunction = 1,
  IllegalDataAddress = 2,
  IllegalDataValue = 3,
  ServerDeviceFailure = 4,
  Acknowledge = 5,
  ServerDeviceBusy = 6,
  MemoryParityError = 8,
  GatewayPathUnavailable = 10,
  GatewayTargetDeviceFailedToRespond = 11,
  NonProtocolError = 255,
};


}
