// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Modbus
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetModbusPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetModbusPayload GetRootAsSetModbusPayload(ByteBuffer _bb) { return GetRootAsSetModbusPayload(_bb, new SetModbusPayload()); }
  public static SetModbusPayload GetRootAsSetModbusPayload(ByteBuffer _bb, SetModbusPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetModbusPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetModbusPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetModbusPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode FunctionCode { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode)__p.bb.Get(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode.None; } }
  public byte UnitIdentifier { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort Address { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte Data(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusPayload> CreateSetModbusPayload(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode function_code = Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode.None,
      byte unit_identifier = 0,
      ushort address = 0,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(4);
    SetModbusPayload.AddData(builder, dataOffset);
    SetModbusPayload.AddAddress(builder, address);
    SetModbusPayload.AddUnitIdentifier(builder, unit_identifier);
    SetModbusPayload.AddFunctionCode(builder, function_code);
    return SetModbusPayload.EndSetModbusPayload(builder);
  }

  public static void StartSetModbusPayload(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddFunctionCode(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode functionCode) { builder.AddByte(0, (byte)functionCode, 0); }
  public static void AddUnitIdentifier(FlatBufferBuilder builder, byte unitIdentifier) { builder.AddByte(1, unitIdentifier, 0); }
  public static void AddAddress(FlatBufferBuilder builder, ushort address) { builder.AddUshort(2, address, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(3, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusPayload> EndSetModbusPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusPayload>(o);
  }
  public static void FinishSetModbusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetModbusPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetModbusPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*FunctionCode*/, 1 /*Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusFunctionCode*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*UnitIdentifier*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*Address*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Data*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
