// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Modbus
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetModbusResponsePayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetModbusResponsePayload GetRootAsSetModbusResponsePayload(ByteBuffer _bb) { return GetRootAsSetModbusResponsePayload(_bb, new SetModbusResponsePayload()); }
  public static SetModbusResponsePayload GetRootAsSetModbusResponsePayload(ByteBuffer _bb, SetModbusResponsePayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetModbusResponsePayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetModbusResponsePayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetModbusResponsePayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode ResponseCode { get { int o = __p.__offset(4); return o != 0 ? (Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode)__p.bb.Get(o + __p.bb_pos) : Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode.Ok; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusResponsePayload> CreateSetModbusResponsePayload(FlatBufferBuilder builder,
      Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode response_code = Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode.Ok,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    SetModbusResponsePayload.AddErrorMessage(builder, error_messageOffset);
    SetModbusResponsePayload.AddResponseCode(builder, response_code);
    return SetModbusResponsePayload.EndSetModbusResponsePayload(builder);
  }

  public static void StartSetModbusResponsePayload(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddResponseCode(FlatBufferBuilder builder, Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode responseCode) { builder.AddByte(0, (byte)responseCode, 0); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusResponsePayload> EndSetModbusResponsePayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusResponsePayload>(o);
  }
  public static void FinishSetModbusResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusResponsePayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetModbusResponsePayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Modbus.SetModbusResponsePayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetModbusResponsePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResponseCode*/, 1 /*Vion.Contracts.FlatBuffers.Hw.Modbus.ModbusResponseCode*/, 1, false)
      && verifier.VerifyString(tablePos, 6 /*ErrorMessage*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
