// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Vion.Contracts.FlatBuffers.Hw.Ao
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetAoPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetAoPayload GetRootAsSetAoPayload(ByteBuffer _bb) { return GetRootAsSetAoPayload(_bb, new SetAoPayload()); }
  public static SetAoPayload GetRootAsSetAoPayload(ByteBuffer _bb, SetAoPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetAoPayload(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetAoPayloadVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetAoPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<Vion.Contracts.FlatBuffers.Hw.Ao.SetAoPayload> CreateSetAoPayload(FlatBufferBuilder builder,
      double value = 0.0) {
    builder.StartTable(1);
    SetAoPayload.AddValue(builder, value);
    return SetAoPayload.EndSetAoPayload(builder);
  }

  public static void StartSetAoPayload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(0, value, 0.0); }
  public static Offset<Vion.Contracts.FlatBuffers.Hw.Ao.SetAoPayload> EndSetAoPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Vion.Contracts.FlatBuffers.Hw.Ao.SetAoPayload>(o);
  }
  public static void FinishSetAoPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Ao.SetAoPayload> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetAoPayloadBuffer(FlatBufferBuilder builder, Offset<Vion.Contracts.FlatBuffers.Hw.Ao.SetAoPayload> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetAoPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
